### ISSUE TITLE
template related error locally and on hackage

### ISSUE THREAD

**Issue by griotspeak** [ninegua/CCA#2]
I cannot install CCA. When I try, I receive this output

`$ cabal install cca
Resolving dependencies...
Downloading syb-0.4.4...
Configuring syb-0.4.4...
Building syb-0.4.4...
Installed syb-0.4.4
Downloading haskell-src-1.0.2.0...
Configuring haskell-src-1.0.2.0...
Building haskell-src-1.0.2.0...
Installed haskell-src-1.0.2.0
Downloading CCA-0.1.5.1...
Configuring CCA-0.1.5.1...
Building CCA-0.1.5.1...
Failed to install CCA-0.1.5.1
Build log ( /Users/tj/.cabal/logs/CCA-0.1.5.1.log ):
Configuring CCA-0.1.5.1...
Building CCA-0.1.5.1...
Preprocessing library CCA-0.1.5.1...
[1 of 4] Compiling Language.Haskell.TH.Instances ( src/Language/Haskell/TH/Instances.hs, dist/build/Language/Haskell/TH/Instances.o )
[2 of 4] Compiling Control.CCA.Types ( src/Control/CCA/Types.lhs, dist/build/Control/CCA/Types.o )
[3 of 4] Compiling Control.CCA.CCNF ( src/Control/CCA/CCNF.lhs, dist/build/Control/CCA/CCNF.o )
[4 of 4] Compiling Control.CCA      ( src/Control/CCA.lhs, dist/build/Control/CCA.o )
In-place registering CCA-0.1.5.1...
Preprocessing executable 'ccap' for CCA-0.1.5.1...
[1 of 7] Compiling State            ( preprocessor/State.hs, dist/build/ccap/ccap-tmp/State.o )

preprocessor/State.hs:7:10: Warning:
    ‘State’ is an instance of Monad but not Applicative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.
[2 of 7] Compiling Utils            ( preprocessor/Utils.lhs, dist/build/ccap/ccap-tmp/Utils.o )
[3 of 7] Compiling ArrCode          ( preprocessor/ArrCode.lhs, dist/build/ccap/ccap-tmp/ArrCode.o )
[4 of 7] Compiling ArrSyn           ( preprocessor/ArrSyn.lhs, dist/build/ccap/ccap-tmp/ArrSyn.o )
[5 of 7] Compiling Lexer            ( preprocessor/Lexer.hs, dist/build/ccap/ccap-tmp/Lexer.o )
[6 of 7] Compiling Parser           ( dist/build/ccap/ccap-tmp/Parser.hs, dist/build/ccap/ccap-tmp/Parser.o )

templates/GenericTemplate.hs:104:22:
    Couldn't match expected type ‘Bool’
                with actual type ‘Happy_GHC_Exts.Int#’
    In the expression:
      (n Happy_GHC_Exts.<# (0# :: Happy_GHC_Exts.Int#))
    In a stmt of a pattern guard for
                   a case alternative:
      (n Happy_GHC_Exts.<# (0# :: Happy_GHC_Exts.Int#))
    In a case alternative:
        n | (n Happy_GHC_Exts.<# (0# :: Happy_GHC_Exts.Int#))
          -> (happyReduceArr Happy_Data_Array.! rule) i tk st
          where
              rule
                = (Happy_GHC_Exts.I#
                     ((Happy_GHC_Exts.negateInt#
                         ((n Happy_GHC_Exts.+# (1# :: Happy_GHC_Exts.Int#))))))

templates/GenericTemplate.hs:115:23:
    Couldn't match expected type ‘Bool’
                with actual type ‘Happy_GHC_Exts.Int#’
    In the expression:
      (off_i Happy_GHC_Exts.>=# (0# :: Happy_GHC_Exts.Int#))
    In the expression:
      if (off_i Happy_GHC_Exts.>=# (0# :: Happy_GHC_Exts.Int#)) then
          (indexShortOffAddr happyCheck off_i Happy_GHC_Exts.==# i)
      else
          False
    In an equation for ‘check’:
        check
          = if (off_i Happy_GHC_Exts.>=# (0# :: Happy_GHC_Exts.Int#)) then
                (indexShortOffAddr happyCheck off_i Happy_GHC_Exts.==# i)
            else
                False

templates/GenericTemplate.hs:117:30:
    Couldn't match expected type ‘Happy_GHC_Exts.Int#’
                with actual type ‘Bool’
    In the expression: False
    In the expression:
      if (off_i Happy_GHC_Exts.>=# (0# :: Happy_GHC_Exts.Int#)) then
          (indexShortOffAddr happyCheck off_i Happy_GHC_Exts.==# i)
      else
          False

templates/GenericTemplate.hs:119:13:
    Couldn't match expected type ‘Bool’
                with actual type ‘Happy_GHC_Exts.Int#’
    In the expression: check
    In a stmt of a pattern guard for
                   a pattern binding:
      check

templates/GenericTemplate.hs:212:14:
    Pattern bindings containing unlifted types should use an outermost bang pattern:
      (sts1@((HappyCons (st1@(action)) (_))))
        = happyDrop k (HappyCons (st) (sts))
    In an equation for ‘happyMonadReduce’:
        happyMonadReduce k nt fn j tk st sts stk
          = happyThen1
              (fn stk tk)
              (\ r -> happyGoto nt j tk st1 sts1 (r `HappyStk` drop_stk))
          where
              (sts1@((HappyCons (st1@(action)) (_))))
                = happyDrop k (HappyCons (st) (sts))
              drop_stk = happyDropStk k stk

templates/GenericTemplate.hs:219:14:
    Pattern bindings containing unlifted types should use an outermost bang pattern:
      (sts1@((HappyCons (st1@(action)) (_))))
        = happyDrop k (HappyCons (st) (sts))
    In an equation for ‘happyMonad2Reduce’:
        happyMonad2Reduce k nt fn j tk st sts stk
          = happyThen1
              (fn stk tk)
              (\ r -> happyNewToken new_state sts1 (r `HappyStk` drop_stk))
          where
              (sts1@((HappyCons (st1@(action)) (_))))
                = happyDrop k (HappyCons (st) (sts))
              drop_stk = happyDropStk k stk
              (off) = indexShortOffAddr happyGotoOffsets st1
              (off_i) = (off Happy_GHC_Exts.+# nt)
              ....
cabal: Error: some packages failed to install:
CCA-0.1.5.1 failed during the building phase. The exception was:
ExitFailure 1`

**Comment by ninegua** [comment]
```
                                                                                  This is caused by a happy preprocessed file left dangling in the dist directory, and it is somehow the default behavior of cabal sdist to pick up this file and stuff it into the distributable. Quite frustrating. But anyway I have removed the file and uploaded a new version to hackage. Please give it a try.BTW, I don't know much about upperbound, and since there is no easy way for me to test it with different GHC versions and library version. I am not inclined to modify the cabal file without knowing what I should put. Thanks for the bug report! I appreciate it.Regards,Paul Liu                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: TJ UsiyanSent: Saturday, January 31, 2015 1:14 PMTo: ninegua/CCAReply To: ninegua/CCASubject: [CCA] template related error locally and on hackage (#2)I cannot install CCA. When I try, I receive this output
```

`$ cabal install cca
Resolving dependencies...
Downloading syb-0.4.4...
Configuring syb-0.4.4...
Building syb-0.4.4...
Installed syb-0.4.4
Downloading haskell-src-1.0.2.0...
Configuring haskell-src-1.0.2.0...
Building haskell-src-1.0.2.0...
Installed haskell-src-1.0.2.0
Downloading CCA-0.1.5.1...
Configuring CCA-0.1.5.1...
Building CCA-0.1.5.1...
Failed to install CCA-0.1.5.1
Build log ( /Users/tj/.cabal/logs/CCA-0.1.5.1.log ):
Configuring CCA-0.1.5.1...
Building CCA-0.1.5.1...
Preprocessing library CCA-0.1.5.1...
[1 of 4] Compiling Language.Haskell.TH.Instances ( src/Language/Haskell/TH/Instances.hs, dist/build/Language/Haskell/TH/Instances.o )
[2 of 4] Compiling Control.CCA.Types ( src/Control/CCA/Types.lhs, dist/build/Control/CCA/Types.o )
[3 of 4] Compiling Control.CCA.CCNF ( src/Control/CCA/CCNF.lhs, dist/build/Control/CCA/CCNF.o )
[4 of 4] Compiling Control.CCA      ( src/Control/CCA.lhs, dist/build/Control/CCA.o )
In-place registering CCA-0.1.5.1...
Preprocessing executable 'ccap' for CCA-0.1.5.1...
[1 of 7] Compiling State            ( preprocessor/State.hs, dist/build/ccap/ccap-tmp/State.o )

preprocessor/State.hs:7:10: Warning:
    ‘State’ is an instance of Monad but not Applicative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.
[2 of 7] Compiling Utils            ( preprocessor/Utils.lhs, dist/build/ccap/ccap-tmp/Utils.o )
[3 of 7] Compiling ArrCode          ( preprocessor/ArrCode.lhs, dist/build/ccap/ccap-tmp/ArrCode.o )
[4 of 7] Compiling ArrSyn           ( preprocessor/ArrSyn.lhs, dist/build/ccap/ccap-tmp/ArrSyn.o )
[5 of 7] Compiling Lexer            ( preprocessor/Lexer.hs, dist/build/ccap/ccap-tmp/Lexer.o )
[6 of 7] Compiling Parser           ( dist/build/ccap/ccap-tmp/Parser.hs, dist/build/ccap/ccap-tmp/Parser.o )

templates/GenericTemplate.hs:104:22:
    Couldn't match expected type ‘Bool’
                with actual type ‘Happy_GHC_Exts.Int#’
    In the expression:
      (n Happy_GHC_Exts.<# (0# :: Happy_GHC_Exts.Int#))
    In a stmt of a pattern guard for
                   a case alternative:
      (n Happy_GHC_Exts.<# (0# :: Happy_GHC_Exts.Int#))
    In a case alternative:
        n | (n Happy_GHC_Exts.<# (0# :: Happy_GHC_Exts.Int#))
          -> (happyReduceArr Happy_Data_Array.! rule) i tk st
          where
              rule
                = (Happy_GHC_Exts.I#
                     ((Happy_GHC_Exts.negateInt#
                         ((n Happy_GHC_Exts.+# (1# :: Happy_GHC_Exts.Int#))))))

templates/GenericTemplate.hs:115:23:
    Couldn't match expected type ‘Bool’
                with actual type ‘Happy_GHC_Exts.Int#’
    In the expression:
      (off_i Happy_GHC_Exts.>=# (0# :: Happy_GHC_Exts.Int#))
    In the expression:
      if (off_i Happy_GHC_Exts.>=# (0# :: Happy_GHC_Exts.Int#)) then
          (indexShortOffAddr happyCheck off_i Happy_GHC_Exts.==# i)
      else
          False
    In an equation for ‘check’:
        check
          = if (off_i Happy_GHC_Exts.>=# (0# :: Happy_GHC_Exts.Int#)) then
                (indexShortOffAddr happyCheck off_i Happy_GHC_Exts.==# i)
            else
                False

templates/GenericTemplate.hs:117:30:
    Couldn't match expected type ‘Happy_GHC_Exts.Int#’
                with actual type ‘Bool’
    In the expression: False
    In the expression:
      if (off_i Happy_GHC_Exts.>=# (0# :: Happy_GHC_Exts.Int#)) then
          (indexShortOffAddr happyCheck off_i Happy_GHC_Exts.==# i)
      else
          False

templates/GenericTemplate.hs:119:13:
    Couldn't match expected type ‘Bool’
                with actual type ‘Happy_GHC_Exts.Int#’
    In the expression: check
    In a stmt of a pattern guard for
                   a pattern binding:
      check

templates/GenericTemplate.hs:212:14:
    Pattern bindings containing unlifted types should use an outermost bang pattern:
      (sts1@((HappyCons (st1@(action)) ())))
        = happyDrop k (HappyCons (st) (sts))
    In an equation for ‘happyMonadReduce’:
        happyMonadReduce k nt fn j tk st sts stk
          = happyThen1
              (fn stk tk)
              (\ r -> happyGoto nt j tk st1 sts1 (r HappyStk drop_stk))
          where
              (sts1@((HappyCons (st1@(action)) ())))
                = happyDrop k (HappyCons (st) (sts))
              drop_stk = happyDropStk k stk

templates/GenericTemplate.hs:219:14:
    Pattern bindings containing unlifted types should use an outermost bang pattern:
      (sts1@((HappyCons (st1@(action)) ())))
        = happyDrop k (HappyCons (st) (sts))
    In an equation for ‘happyMonad2Reduce’:
        happyMonad2Reduce k nt fn j tk st sts stk
          = happyThen1
              (fn stk tk)
              (\ r -> happyNewToken new_state sts1 (r HappyStk drop_stk))
          where
              (sts1@((HappyCons (st1@(action)) ())))
                = happyDrop k (HappyCons (st) (sts))
              drop_stk = happyDropStk k stk
              (off) = indexShortOffAddr happyGotoOffsets st1
              (off_i) = (off Happy_GHC_Exts.+# nt)
              ....
cabal: Error: some packages failed to install:
CCA-0.1.5.1 failed during the building phase. The exception was:
ExitFailure 1`

—Reply to this email directly or view it on GitHub.
